### ISSUE TITLE
Provide an example of camera positionning on demo load

### ISSUE THREAD

**Issue by EricBoix** [VCityTeam/UD-Viz#120]
### The need
The underlying need is to point to a reduced dataset in order to avoid comple scene data loading.

### Technical detail
Provide the couple lines that a some_demo.js code should hard-code in order to easily position the camera pointing to the area of interest.

Most of the elements already exist: refer to
 - [CameraPositioner demo](https://github.com/VCityTeam/UD-Viz/blob/master/examples/CameraPositionerWidget/example.html)
 - Positioning the camera is [done within PositionerWindow.js](https://github.com/VCityTeam/UD-Viz/blob/master/src/Widgets/Components/Camera/PositionerWindow.js#L117)

**Comment by EricBoix** [comment]
VJA said: attention le mode par [défaut dans iTowns](https://github.com/MEPP-team/UDV/blob/master/UDV-Core/src/Utils/BaseDemo/js/BaseDemo.js#L479) cela est fait différement.

CCO: peut-être faut-il simplement mettre un nouveau champ correspondant dans le fichier config de base demo ?

VJA: comment aligner les coordonnnées de la caméra dans [itowns/UDV](https://github.com/MEPP-team/UDV/blob/master/UDV-Core/src/Utils/BaseDemo/js/BaseDemo.js#L479) avec celle du caméra positionner ?

**Comment by johnsamuelwrites** [comment]
Ideally, we could also have an attribute 'position' in the URL.

demo.html?position=a,b,c

Hint: window.location.search() can give the URL parameters

**Comment by EricBoix** [comment]
CCO: maybe the way to go is to extend the configuration file of base demo with such positions ?

**Comment by valentinMachado** [comment]
Could be related to #162 

Today camera can have a default transform (with the itowns system) if nothing is passed or base on a config file. (see #162)

> VJA said:
> 
> Note that [the iTowns way of dealing with the camera/direction](https://github.com/MEPP-team/UDV/blob/master/UDV-Core/src/Utils/BaseDemo/js/BaseDemo.js#L479) is different from the UDV/CameraPositionner logic.
> 
> What is the proper way of aligning the [itowns/UDV way](https://github.com/MEPP-team/UDV/blob/master/UDV-Core/src/Utils/BaseDemo/js/BaseDemo.js#L479) with the logic of the CameraPositioner ?

itowns has a different way of handling camera transform since the elevation (position.z) is computed relatively with the ground and not in an absolute way like in ud-viz.
https://github.com/iTowns/itowns/blob/6f4ec34128f82c6c997a6dbb53cae9e87a15bdc6/src/Utils/CameraUtils.js#L310
Meaning there is no way to align ud-viz and itowns on this since the ground elevation depends of an external ressources (an elevation layer).

I don't understand the relationship with the CameraPositioner @EricBoix ?
To modify the default camera transform, you would have to edit this file (and write the default camera transform in itowns system):
https://github.com/VCityTeam/UD-Viz/blob/master/packages/browser/examples/assets/config/frame3D_planars.json

> Ideally, we could also have an attribute 'position' in the URL.
> 
> demo.html?position=a,b,c
> 
> Hint: window.location.search() can give the URL parameters

Yeah this could be a nice feature, should I close this and open an issue on that ?
We could also use localStorage (with the last camera tranform updated) ?

**Comment by valentinMachado** [comment]
Two features have been implemented #619 and #620 to set camera matrix when the SideBarWidget application is initializing. Is this still relevant ? @EricBoix @clementcolin

**Comment by valentinMachado** [comment]
EBO said: The aim of this issue is to produce a documentation to explain how to place the default camera position at the start of the application (SideBarWidget)

**Comment by EricBoix** [comment]
Exactly @valentinMachado .  Since the feature now exists, it suffice to document it. And maybe  that this (documentation related) information (a couple lines no more) could be placed in a `HowTo.md` file that could be placed in e.g. the [docs/static/user directory](https://github.com/VCityTeam/UD-Viz/tree/master/docs/static/User) ?
Please do mention the four ways to do so:
* plain old config file, 
* local storage, 
* URL positional arguments and 
* [this one (?)](https://github.com/VCityTeam/UD-Viz/pull/620)

**Comment by valentinMachado** [comment]
>And maybe that this (documentation related) information (a couple lines no more) could be placed in a `HowTo.md` file that could be placed in e.g. the [docs/static/user directory](https://github.com/VCityTeam/UD-Viz/tree/master/docs/static/User) ? 

I am not sure this is a user oriented documentation since we are explaining the application API (interaction with code). From what I've understood a user documentation is to explained how to interact with the application itself (like this [one](https://github.com/VCityTeam/UD-Viz/blob/master/docs/static/User/ContributeData.md)). Imo this belong to `docs/static/dev/ud_viz_browser/application_name.md`

I think all application provided by @ud-viz/browser (today `SideBarWidget`) should have a user documentation in `docs/static/user/application_name.md` that explain how to interact with the application.

**Comment by EricBoix** [comment]
@valentinMachado I agree, I was flaky about my definition of user. Since UD-Viz is made of packages (as opposed to applications) the ones using UD-Viz will be developers building their respective applications. I labelled such developers "users of UD-Viz". I should have said developers using the UD-Viz packages. This is to be opposed to "developers of UD-Viz" i.e. the subset of developers that contribute to UD-Viz (per se).
And the documentation explain how to define some default camera position at the start of the application will be used by developers of UD-Viz based application i.e. developers using the UD-Viz packages.

**Comment by valentinMachado** [comment]
Doc has been produced on this [branch](https://github.com/VCityTeam/UD-Viz/tree/documentation_3_1)

**Comment by EricBoix** [comment]
As discussed in tech meeting, what is called user documentation (refer to [docs/static/User](https://github.com/VCityTeam/UD-Viz/blob/master/docs/static/User/ContributeData.md)) concerns the usage of UD-Viz and is thus close to the application. If we where to use within UD-Viz, it would belong "inside" an "application"  (refer to [showdown npm package](https://www.npmjs.com/package/showdown)) or inside the examples.
Thus move the [docs/static/User/ContributeData.md](https://github.com/VCityTeam/UD-Viz/blob/master/docs/static/User/ContributeData.md) code to [examples/asset/doc](https://github.com/VCityTeam/UD-Viz/tree/master/examples/assets) directory, break in down in example related chunks, and integrate such chunks (with e.g. [showdown npm package](https://www.npmjs.com/package/showdown)) to its respective example.
