### ISSUE TITLE
Handling multiple layers / tilesets

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#137]
As it is right now, the tiles manager class only handle [one layer](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/src/Utils/3DTiles/TilesManager.js#L26)
In order to be able to easily use multiple source and perform action on those layers, such as select objects, there is a need to think at a solution to handle multiple layers.
It can be fixed either by extending the [layer](https://github.com/VCityTeam/UD-Viz/blob/master/UD-Viz-Core/src/Utils/3DTiles/TilesManager.js#L26) attribute as a list, thus modifying inherent methods, or by creating a layer manager, able to handle multiples TilesManager, which seems to be a lot more work to do.

**Comment by jailln** [comment]
IMO the second solution is simpler since you won't have to update the TilesManager nor the other [3D Tiles Utils](https://github.com/VCityTeam/UD-Viz/tree/master/UD-Viz-Core/src/Utils/3DTiles) which use it. 
In addition, this "layer manager" module could be a bit more generic and allow to manage other layers than 3D Tiles ones (e.g. WMS layers) and to allow operations on them too (maybe something similar to what can be done in itowns examples (e.g. [here](http://www.itowns-project.org/itowns/examples/index.html#source_stream_wfs_3d))); which I think will be needed by @Khadath and @HomereB.
