### ISSUE TITLE
Automatically handle projection system from 3DTiles

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#186]
As we expect 3DTiles to have the geospatial coordinates in the tileset and tiles placed relatively to this position, it would be possible to read the projection system in the tileset and convert it in a generic projection system (such as WGS:84) using proj4

**Comment by valentinMachado** [comment]
Is there a projection system (crs) in a tileset ? I understood that tileset.json is encoding a spatial transformation with boudingVolume attributes in tileset.json. Maybe I just don't understand what you mean.
related #260

**Comment by valentinMachado** [comment]
@clementcolin If I understand well you propose that tileset.json register crs used to project 3DTiles, and then in ud-viz it would be possible to modify this crs on the fly, by unprojecting then reprojecting.

This imply to modify code in itowns since its itowns that is managing 3DTiles load and add to the three.js scene.

I think it would be better to generate a new tileset.json if you need to modify a crs.
Let me know if you agree so we can close this or open an issue in itowns.

**Comment by clementcolin** [comment]
Yes, it was exactly what I meant.

It suppose to add a 3D Extension that allows to specify the projection system (crs) in the bounding volume / position of a Tile.
Anyway, you are right, this issue needs to live in itowns, so i am closing this issue.
