### ISSUE TITLE
Update 3DTiles debug widget

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#191]
Itowns [provides some functions](https://github.com/iTowns/itowns/blob/6953e0119c35a550621aa792a204c352731aca97/utils/debug/3dTilesDebug.js) to debug 3DTiles that may be added to the 3DTiles debug widgets.

**Comment by valentinMachado** [comment]
If their debug 3D tiles widget is better why not using it directly ?
If our implements some features that their widget don't, we should then contribute to their 3D tiles debug widget.

**Comment by valentinMachado** [comment]
Iam currently cleaning debugView in #584 on this [branch](https://github.com/VCityTeam/UD-Viz/tree/584-clean-itowns-folder) and I think we should stop supporting it since itowns has an equivalent. If itowns debug 3DTiles widget is not doing what we need we should then contribute. @clementcolin do you agree on deleting our debug3DTiles widget (which is not doing so much anyway) and if you some needs not cover by the itowns 3DTiles debug open a discussion overthere / discussion ?
