### ISSUE TITLE
Local avatar controls

### ISSUE THREAD

**Issue by webanck** [VCityTeam/UD-Viz#249]
Hello, from the [localGame example](https://github.com/VCityTeam/UD-Viz/blob/master/examples/LocalGame.html) I am implementing dynamic collisions between the player avatar and the buildings tiles. Because the tiles are loaded in the local/game view/client context, it is simpler to check for collisions in this local context rather than in the world/server context.

## Description of the current process behind avatar controls
Pressing the 'z' key currently spawns a command sent from the local to the world context. Then, the command is applied to the avatar by translating it according to the time passed, thus updating the position of the avatar in the world context. Finally, the new world state is sent from the world context to the local context, this time updating the position of the avatar in the game view.

## Problem, explored approaches, and suggestion
With the current process behind avatar controls, it is impossible to compute collisions locally. Now, multiple approaches are possible to remedy this:
- Compute the collisions in the world context.
  - Problem: would require the world/server to load the same tiles as the client(s).
- Compute the collisions and translation in the local context and send the updated position to the world context.
  - Problem: from my tests, this adds violent stuttering/rollback of the avatar because during the whole local-world-local round trip done to update the position of the avatar, new commands are still prepared from the local context with out of date positions.
- Same as previous but update the position directly in the local context, thus only notifying the server of the new position (for multiplayer support).

The last approach is my personal suggestion to allow proper local avatar controls while still tracking positions of local elements such as the avatar in the world context.
Implementing this might require modifying the game view manager to separate game objects controlled locally from the others and avoiding to update their positions from the world state updates.
Filtering out the game objects controlled locally from the world state updates could in theory be done with only one player but multiple players would need different world state updates.

**Comment by valentinMachado** [comment]
I am closing this since there is now a flag noLocalUpdate which prevent local context to update a gameobject. A local implementation has been made in the ud-viz example.

To make it work in multiplayer the server would have to filter for each avatar the one to tag with the flag noLocalUpdate and each avatar in a localscript (local context) should send to the server a command "update transform" to notify server (world context) to place the avatar at the new transform (so the other player actually see changes of eachother). Meaning all code needed (except the command type "update transform" which could be add on purpose) has been produced.
