### ISSUE TITLE
Reproducing iTowns 3DTiles projection/transformation to Three.js 3D scene

### ISSUE THREAD

**Issue by webanck** [VCityTeam/UD-Viz#260]
I am trying to place a 3D model at specific geographic coordinates, in the same referential as the 3DTiles of Lyon loaded in UD-Viz.

I currently describe my GLB model asset in the `local_game_config.json` file and it is effectively loaded as I can see it in the 3D view of UD-Viz when setting the anchor parameter as `min` for instance.

The problem is that the real coordinates of the model lie in the same referential as the 3DTiles of Lyon as it originates from such a tile. Those coordinates are in the order of the million in X and Y (horizontal) axes, and the model is too far to be visible in the 3D view of UD-Viz without anchor.

I need to reproduce the transformation applied by iTowns to pass from the referential of the 3DTiles to the referential of the Three.js scene.
From what I gathered yet, the 3DTiles of UD-Viz use the `EPSG:3946` projection standard (see the `projection` parameter of the `3DTilesLayers` in the `local_game_config.json` file). [More on the projection standards on wikipedia](https://fr.wikipedia.org/wiki/Projection_conique_conforme_de_Lambert).

**Comment by webanck** [comment]
In fine, the situation is more simple than I previously thought: there is in fact no transformation applied by iTowns to the 3DTiles loaded. In other words, the models in the 3DTiles AND the camera are positioned at geospatial coordinates, implicitly considering that all share the `EPSG:3946` projection standard.

A latent problem is the incompatibility between different versions of the EPSG projection standard or even different CRS. How should we load and merge tiles using the `EPSG:3946`, `EPSG:3857` and `EPSG:4326` standards for instance? If I recall correctly, DeckGL for instance is not using the same CRS as UD-Viz. So should we reproject the loaded data on the fly in a unifying CRS?

**Comment by DiegoVinasco** [comment]
bumping closed duplicate #263 ☝🏽

**Comment by valentinMachado** [comment]
There is no crs in a 3DTiles set, transformation is included in the format.
These transformation are encoded in boundingVolume => box and are 12 number (a matrix 3*4 ?)
@LorenzoMarnat am I correct ?
Meaning 3DTiles are directly add to the Three.js scene.
We could transform all 3D model (.obj, gltf,...) in 3DTiles using [py3DTilers](https://github.com/VCityTeam/py3dtilers).

Nevertheless I see input format for py3DTilers is obj files and not gltf/glb like in [UD-IMUV](https://github.com/VCityTeam/UD-Imuv), the questions is there a way to keep material texture + animation encapsulated in glb in 3DTiles after the conversion ?

**Comment by LorenzoMarnat** [comment]
> There is no crs in a 3DTiles set, transformation is included in the format. These transformations are encoded in tileset.json => boundingVolume => box and are 12 number (a matrix 3*4 ?) 

That's right, in the tileset.json each tile has a `transform` (4*4 matrix) attribute, used to apply a transformation to the glTF content of the tile. In the glTF, all the coordinates are 'normalized' (centered around [0,0,0]) and the `transform` is used to put the meshes on geospatial positions.

> Meaning 3DTiles are directly add to the Three.js scene. We could transform all 3D model (.obj, gltf,...) in 3DTiles using [py3DTilers](https://github.com/VCityTeam/py3dtilers).
>
> Nevertheless I see input format for py3DTilers is obj files and not gltf/glb like in [UD-IMUV](https://github.com/VCityTeam/UD-Imuv), the questions is there a way to keep material texture + animation encapsulated in glb in 3DTiles after the conversion ?

I think there are 3 possible solutions to load gltf/glb models in UD-Viz:

- Have geospatial coordinates in the gltf/glb. !!Warning: since glTF coordinates are encoded as float32, using geospatial positions can cause precision issues (that's why we use the `transform` attribute in our tileset.json)
- Create a `glb/gltf Tiler` in Py3DTilers: 3DTiles is glTF encapsulated in B3DM files. If we have a glTF file as input, we could easily create a 3DTiles by creating a small tileset.json with transform attributes
- Create an 'editor' in UD-Viz (similar to the IMUV editor ?) to load 3D models and add transformations

**Comment by clementcolin** [comment]
> Create a glb/gltf Tiler in Py3DTilers: 3DTiles is glTF encapsulated in B3DM files. If we have a glTF file as input, we could easily create a 3DTiles by creating a small tileset.json with transform attributes

Just FYI : in 3DTiles next the B3DM part will disappear to only keep the gltf part. Maybe we can already work to create 3DTiles with gltf files in tile directly ?

**Comment by EricBoix** [comment]
See also the [embryonic howto](https://github.com/VCityTeam/UD-SV/blob/master/ImplementationKnowHow/WorkingWithGeographicalData.md)...

**Comment by EricBoix** [comment]
Solving this issue is a two steps process:
1. retrieve the information defining the transformation matrix (translation + rotation) that must be applied to the [gltf/glb](https://en.wikipedia.org/wiki/GlTF) (geographical object using non geographic coordinates (that is coordinates relative to the geometry editor e.g. 3DS or Blender)
2. express that transformation matrix as a 3DTiles thin wrapper pointing to the gltf/glb file and adding a [3DTiles transform matrix](https://github.com/CesiumGS/3d-tiles/tree/main/specification#transforms).
   
The first repositioning step could be done by adapting the [Slideshow widget](https://github.com/VCityTeam/UD-Viz/blob/master/examples/SlideShowWidget.html) to extend/generalize the repositioning of an image in a geographic scene to repositioning a gltf/glb geometry. This generalization should come at a reduce cost since the gltf/glb scene loading can be done with Three.js (is supported by threejs). This generalized repositioning widget could then offer to copy paste the json based version of the 3dTiles transform matrix.

The second step, for the production of 3dTiles thin wrapper could
* either be done manually by editing a 3dTiles template to replace the transformation matrix snippet as well as referencing the glb/gltf file.
* or be done with py3dTilers through the usage of the [offset option](https://github.com/VCityTeam/py3dtilers/tree/master/py3dtilers/Common#offset)

Important notice: the above proposition only deals with translation transpositions to geographic coordinates but eludes the possibly required rotation components. Refer to the [option to rotate the output 3D Tiles](https://github.com/VCityTeam/py3dtilers/issues/134) py3dTilers issue.

**Comment by valentinMachado** [comment]
I've done an application in this [PR](https://github.com/VCityTeam/UD-Viz/pull/656) allowing to edit the transformation of a gltf loaded from the local disk. then to download the transformation edited as a json file (the format exported could evolved to fit the intended format of py3DTilers though). Imo the second step is out of the scope of @ud-viz since it's up to the user to produce such 3DTiles.
