### ISSUE TITLE
Can the hard coded values in the elevation layer be customized?

### ISSUE THREAD

**Issue by DiegoVinasco** [VCityTeam/UD-Viz#264]
When looking at the function for [adding a new elevation layer](https://github.com/VCityTeam/UD-Viz/blob/ce4460b8ab8f728d2286f31e7078a642fbae9e07/src/Views/View3D/View3D.js#L519) several fields in the layer are hardcoded, like `colorTextureElevationMaxZ: 622`.

What do the `colorTextureElevation` fields do and would there ever be a case when they should change? For example with a 3DTiles dataset that has a vastly different elevation or when using a different WMSSource?

If so, perhaps these fields could be optionally set in the configuration file?

**Comment by clementcolin** [comment]
Actually, an elevation layer is the same thing as a [heightmap](https://en.wikipedia.org/wiki/Heightmap). It is an image representing the ground height at a given position, using grey scale. As it is in an image, the value of a pixel is either between 0 and 1 or between 0 and 255.
The `colorTextureElevationMaxZ` field helps to reproject the height value of a pixel, so that we are not constraint between 0 and 1 or 255. Its value should be the same as the height of the higher point in the image.

We would need to change it if we use other elevation Layer (or heightmap) that different data. For example, if you find a heighmap of the Alps, there is a chance that the ground is between 500 meters and 4 800 meters.

However, we should be able to set these fields in the configuration file.

**Comment by ggesquiere** [comment]
+1

**Comment by DiegoVinasco** [comment]
Ok that makes sense, thanks!

In that case, I think we could leave this issue open as a potential enhancement to allow modifying the default values.

**Comment by valentinMachado** [comment]
These values can now be configured in config
