### ISSUE TITLE
Create a 2D visualization mode

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#312]
Not all 3D data have an altitude, meaning that some are "flying" and some are not when not using the elevation layer.

It would be nice to provide a feature to "put on the ground" each tileset, or set their altitude at 0,

**Comment by valentinMachado** [comment]
How do you detect that a 3D data (<= 3DTiles you mean ?) does not have an altitude ?

**Comment by valentinMachado** [comment]
Ok so if I understand well, an object3D (3DTiles or THREE.Object3D) does not have an altitude if the lower point of the object3D is above the higher point of the elevation layer (in the xy square of the object3D) right ?

And if it does not have an altitude then we translate the object3D on the z axis of obj3d_lower_point.z - elevation_layer_higher_point.z something like that ?

I think this will works for object3D on a flat ground.

![dessin](https://user-images.githubusercontent.com/14295096/233137980-d0749311-f94c-428a-ba61-f40f4f765bba.png)

here you can first see my art skill and take a moment to appreciate

then in that case the building in red (lower point in yellow) and the ground in gray (higher point in green) are not matching the "flying" condition and as you can see we could translate this building to "put it on the ground"

one approach could be to divide the area in several sub area and to operate the same algorithm (as we could consider the more we divide the more the ground will be flat) then do an average of the translation amount on the z axis.

Another thing I am thinking about is as 3DTiles wrapped their own transformation we don't want to move them..
Typically we move the 3DTiles everything is fine, the 3DTiles unload the 3DTiles reload and now it's flying again.

So I guess the right approach would be to move the elevation layer (I don't know how without deleting recreating the layer but should be manageable)

**Comment by valentinMachado** [comment]
That's explain why I was still not getting the title ^^

The computation of this translation is quite simple as you said, the tricky part here I guess is to detect when an object3d is added to the scene (to run the translate computation when needed and only for the new object3d concerned to make it fully automatic and performant). With 3DTiles is quite simple since it exists a [ON_TILE_CONTENT_LOADED](https://github.com/iTowns/itowns/blob/b39edf81d97c9fca320c751fc3df4f56fd8d2a64/src/Layer/C3DTilesLayer.js#L17) and for all itowns layer which have an object3D looks like the object3D is added [here](https://github.com/iTowns/itowns/blob/b39edf81d97c9fca320c751fc3df4f56fd8d2a64/src/Core/View.js#L347) so by wrapping the addLayer method of itowns and listening the tile loaded event we could trigger the computation when needed.. but if we want to propose this feature to ud-viz user they could add object3d anywhere on the fly causing problems of this feature 

three js PR about generic object3D add/remove detection [here](https://github.com/mrdoob/three.js/pull/16934)

so I think we should just propose the translate computation function to the user and is up to him/her to call it when it's needed.

Would it satisfy the need here ?

**Comment by clementcolin** [comment]
Yes, totally. Maybe i'll propose this feature in Itowns as a ThreeUtils.

**Comment by LorenzoMarnat** [comment]
For information, the [GeoJSON Tiler](https://github.com/VCityTeam/py3dtilers/tree/master/py3dtilers/GeojsonTiler) of Py3DTilers allows to set the altitude where will be placed the features ([`--z` flag](https://github.com/VCityTeam/py3dtilers/tree/master/py3dtilers/GeojsonTiler#properties)):

```bash
geojson-tiler -i buildings.geojson --z 0
```

This will create a 3D Tiles where all the features are at 0 meter (this option was used to create [this Py3DTilers example](https://py3dtilers-demo.vcityliris.data.alpha.grandlyon.com/html/wide.html)).

Maybe it will be interesting to have this option available for all Tilers

**Comment by clementcolin** [comment]
It could be usefull for users of Py3DTilers, the best tiler in the world, but I dont think this solves this issue, as 3DTiles can come from many different origins (because there is so many external user).
In my mind, we could set all geometry to altitude 0 in ud-viz to create a 2D Mode that avoid floating object.
Another solution could be to use the height map to set the altitude of an object at its position. 
This would fix either floating object when a user does not want elevation, or to elevate objects with no altitude when the user wants elevation.
