### ISSUE TITLE
Do not import CSS from Widgets  

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#341]
Currently, the CSS of a widget is integrated/included with its Widgets (refer e.g. [here](https://github.com/VCityTeam/UD-Viz/blob/master/src/Widgets/GuidedTour/GuidedTour.js#L7) ). 
This approach makes it hard to customize such CSS when creating an application using a widget.

iTowns handles things a differently: the [single .css file](https://github.com/iTowns/itowns/blob/master/examples/css/widgets.css) (regrouping all the CSS of all the widgets) is provided separately from the widget behavior (js code) and is referenced in the [html file of the examples](https://github.com/iTowns/itowns/blob/master/examples/widgets_navigation.html#L14).

In order to allow for widget CSS customization, UD-Viz could adopt iTowns' practice and refrain from importing the CSS from the JS widget code.

Furthermore, this behavior and problematic can be extended to UD-Viz widget's derived file, such as the [AllWidget](https://github.com/VCityTeam/UD-Viz/blob/master/src/Templates/AllWidget/AllWidget.js#L11) template.

Additionally, I one wishes to get clother to iTowns, the currently separated css of all widgets in the '[examples/assets](https://github.com/VCityTeam/UD-Viz/tree/master/examples/assets)' could be regrouped in a single CSS file they way iTowns does it.

**Comment by valentinMachado** [comment]
In the PR I proposed https://github.com/VCityTeam/UD-Viz/pull/563 there are 3 places to declare css.

In Widget code: this css is mandatory for the widget, like the document visualizer which has to be at the center of the screen, note that we want this css to be as minimal as possible since to override it, it will be such a pain. (If we find a case where this css is conflicting we should consider to remove it from widget css)

In Template code (AllWidget aka SideBarWidget): A template is a high level object and can define how widget looks like, if we want to customize it we could think about a way to override template (with css variable maybe) or the user has to be create a new template.

Out of sources (in html): Here the user do what he wants with css, in the PR there is a default.css in examples/assets/css which define:

```css
body{
overflow:hidden;
}
```
Since we don't want (even for template) to define css behavior globally here body, this is the right place to write it.

I attach this issue to the PR so when it merged it should close this.
