### ISSUE TITLE
TilesManager.EVENT_TILE_LOADED return a THREE.Object3D

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#580]
The [load tile](https://github.com/VCityTeam/UD-Viz/blob/master/packages/browser/src/Component/Itowns/3DTiles/TilesManager.js#L118) method of the TilesManager aims to create a [Tile](https://github.com/VCityTeam/UD-Viz/blob/master/packages/browser/src/Component/Itowns/3DTiles/Model/Tile.js) and send an event when this Tile is created.

- /!\ The tile that is created here is not the geometry, as it takes in the parameter a tile which is a THREE.Object3D
- /!\ The event returns the THREE.Object3D tile

Therefore, the tile that is sent with the event should be the one created, i.e the one holding the style, city object and the THREE.Object3D tile.   

In the meanwhile, it is also interesting to note that Itowns does not have event send when the geometry of a tile is loaded from the network and loaded  in the scene [ref](https://github.com/iTowns/itowns/blob/284be24da70ca09c1a710b9f7be237bb5935bd39/src/Process/3dTilesProcessing.js#L8)

Fixing this may break a lot of feature and demo already working.

**Comment by valentinMachado** [comment]
maybe related to #342 ?

**Comment by valentinMachado** [comment]
I am closing this since TilesManager and Tile class of @ud-viz/browser have been removed with this [PR](https://github.com/VCityTeam/UD-Viz/pull/612), meaning there are not cityObject cityObjectStyle anymore.

You may want to use the new itowns API done within that [PR](https://github.com/iTowns/itowns/pull/2060) to apply style to your 3DTiles object3D (using [C3DTFeature](https://github.com/iTowns/itowns/blob/master/src/Core/3DTiles/C3DTFeature.js) and [Style](https://github.com/iTowns/itowns/blob/master/src/Core/Style.js)), and also listen to the new C3DTilesLayer event [ON_TILE_CONTENT_LOADED](https://github.com/iTowns/itowns/blob/23c16d2bc188bf200011167db6692686d2782163/src/Layer/C3DTilesLayer.js#L17) which is trigger when object3D of a tile (also call tilecontent) has been loaded.
