### ISSUE TITLE
SPARQL Widget: clicking on building nodes should hide the 3dtilesets that do not contain the building geometry

### ISSUE THREAD

**Issue by DiegoVinasco** [VCityTeam/UD-Viz#635]
For example the online [Gratte Ciel demo](https://demo.liris.cnrs.fr/vcity/ud-demo-graph-static/) uses 4 3dtilesets (2009, 2012, 2015, 2018)

When clicking a building node with all of the layers visible, we see highlighted overlapping geometry:

![image](https://user-images.githubusercontent.com/23373264/235159905-cdf0832b-f6cc-462c-9312-b40f17d8f640.png)

Desired behavior: when clicking on a building node, layers should be hidden that do not contain the geometry associated with the node (e.g., by batch table `gmlid` lookup for CityGML buildings)

For example :

![image](https://user-images.githubusercontent.com/23373264/235160486-b6dabab5-01d0-4a7e-a2ec-f4d8f226ae95.png)

**Comment by valentinMachado** [comment]
Your screenshots seems to be not up to date with the current ud-viz version.
Moreover with this [PR](https://github.com/VCityTeam/UD-Viz/pull/612) style application (coloring features) has been removed from the SPARQL widget and move to the SideBarWidget class [here](https://github.com/VCityTeam/UD-Viz/blob/99ff52f3b5fab5f0fd73ea237a490916847a7c10/packages/browser/src/SideBarWidget/SideBarWidget.js#L37) for now only a simple selection is handle.
This has been done since coloring features should be up to the application (here SideBarWidget) and not the widget (avoiding conflict between widgets). In that case SPARQL widget should dispatch an event FEATURE_CLICKED (<== something like that) and the application should register in that event to handle style.

**Comment by DiegoVinasco** [comment]
That's correct, I forgot to mention that this issue is in relation to the changes being proposed to the SPARQL widget in [this branch](https://github.com/VCityTeam/UD-Viz/tree/workspaces-integration) and I'm realizing that this issue is actually use-case specific to certain online SPARQL demos. 

So I'm going to migrate this issue to the [relevant repositories](https://github.com/VCityTeam/UD-Demo-Graph-Static-docker/issues/1) and close it here.

Otherwise, you're correct and as the branch is updated to be able to merge it, the color selection should be resolved like you mentioned.

(Ping @CorentinGaut)
