### ISSUE TITLE
Starting position does not reset after clearing the cache 

### ISSUE THREAD

**Issue by clementcolin** [VCityTeam/UD-Viz#701]
In the ShowRoom example, we currently save the starting position in the local storage when exiting the app, which is the expected behavior.

However, when clearing the cache and/or refreshing the window without the cache, the position is kept in the local storage. I do think that it should also be cleared to completely reset the application context.

**Comment by JPugetGil** [comment]
Maybe we should create a `Bookmark` widget where the user can store a list of locations.
The user can select a bookmark from this list to represent the camera's starting point.

**Comment by valentinMachado** [comment]
Clearing the cache is currently not working because this feature is listening the [closing tab event](https://github.com/VCityTeam/UD-Viz/blob/94ce5e93902118c5c9403125164fe893dd384de0/packages/browser/src/LocalStorageUtil.js#L24) and register the starting camera matrix4 at this moment.   

>Maybe we should create a Bookmark widget where the user can store a list of locations.
>The user can select a bookmark from this list to represent the camera's starting point.

I agree, I'll implement a solution like this it should solve this issue.
